spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  cache:
    redis:
      cache-null-values: true
      enable-statistics: false
      key-prefix:
      time-to-live: 1d
      use-key-prefix: off
    cache-names:
    type: redis

redis:
  enable: true
  cache:
    enable: false
  session:
    enable: true

