spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    # Since 2.0.0.RELEASE ,default use lettuce
    # jedis:
    #   pool:
    #     min-idle: 0
    #     max-idle: 8
    #     max-active: 8
    #     max-wait: -1ms
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  cache:
    type: redis
    cache-names: springboot
    redis:
      time-to-live: 1h
      cache-null-values: false
      enable-statistics: false
      key-prefix: redis
      use-key-prefix: off
