/*
 * This file is generated by jOOQ.
 */
package com.xbw.spring.boot.project.jooq.tables.records;


import com.xbw.spring.boot.project.jooq.tables.Users;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>springboot.users.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>springboot.users.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>springboot.users.user_code</code>.
     */
    public void setUserCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>springboot.users.user_code</code>.
     */
    public String getUserCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>springboot.users.user_name</code>.
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>springboot.users.user_name</code>.
     */
    public String getUserName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Users.USERS.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return Users.USERS.USER_CODE;
    }

    @Override
    public Field<String> field3() {
        return Users.USERS.USER_NAME;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getUserCode();
    }

    @Override
    public String component3() {
        return getUserName();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getUserCode();
    }

    @Override
    public String value3() {
        return getUserName();
    }

    @Override
    public UsersRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UsersRecord value2(String value) {
        setUserCode(value);
        return this;
    }

    @Override
    public UsersRecord value3(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public UsersRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Long userId, String userCode, String userName) {
        super(Users.USERS);

        setUserId(userId);
        setUserCode(userCode);
        setUserName(userName);
    }
}
