#debug: true
spring:
  profiles:
    active: mysql

# MyBatis
# when use mybatis-plus, mybatis config is inactive
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.xbw.spring.boot.**.model
mybatis-plus:
#  config-location: ${mybatis.config-location}
  mapper-locations: ${mybatis.mapper-locations}
  type-aliases-package: ${mybatis.type-aliases-package}
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
#    object-wrapper-factory: com.baomidou.mybatisplus.extension.MybatisMapWrapperFactory