#debug: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-master?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    jdbc-url: ${spring.datasource.url}
    username: root
    password:


#beetlsql:
#  sqlManagers: default
#  default:
#    basePackage: com.xbw.spring.boot.**.mapper
##    daoSuffix: Mapper # default Mapper
#    ds: dataSource

beetlsql:
  sqlManagers: sqlManager
  sqlManager:
    basePackage: com.xbw.spring.boot.**.mapper
#    daoSuffix: Mapper # default Mapper
    ds: dataSource
