#debug: true
spring:
  jms:
    pub-sub-domain: false # Default false
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: true
    packages:
      trust-all: true
    pool:
      enabled: false