# H2
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.h2/test/camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
    username: sa
    password:
  h2:
    console:
      enabled: true
