# Oracle
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username:
    password:
  sql:
    init:
      mode: never
      schema-locations: classpath:db/schema-oracle.sql