<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
             xmlns:wsp="http://www.w3.org/ns/ws-policy"
             xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:tns="http://jaxws.project.boot.spring.xbw.com" xmlns="http://schemas.xmlsoap.org/wsdl/"
             targetNamespace="http://jaxws.project.boot.spring.xbw.com" name="HelloService">

    <wsp:Policy wsu:Id="HelloServiceSoapBinding_MTOM_Policy">
        <ns1:OptimizedMimeSerialization
                xmlns:ns1="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization"
                wsp:Optional="true"></ns1:OptimizedMimeSerialization>
    </wsp:Policy>
    <types>
        <xs:schema xmlns:tns="http://jaxws.project.boot.spring.xbw.com"
                   xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0"
                   targetNamespace="http://jaxws.project.boot.spring.xbw.com">
            <xs:element name="sayHello" type="tns:sayHello"></xs:element>
            <xs:element name="sayHelloResponse" type="tns:sayHelloResponse"></xs:element>
            <xs:complexType name="sayHello">
                <xs:sequence>
                    <xs:element name="text" type="xs:string" minOccurs="0"></xs:element>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="sayHelloResponse">
                <xs:sequence>
                    <xs:element name="return" type="xs:string" minOccurs="0"></xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </types>
    <message name="sayHello">
        <part name="parameters" element="tns:sayHello"></part>
    </message>
    <message name="sayHelloResponse">
        <part name="parameters" element="tns:sayHelloResponse"></part>
    </message>
    <portType name="HelloService">
        <operation name="sayHello">
            <input wsam:Action="sayHello" message="tns:sayHello"></input>
            <output wsam:Action="http://jaxws.project.boot.spring.xbw.com/HelloService/sayHelloResponse"
                    message="tns:sayHelloResponse"></output>
        </operation>
    </portType>
    <binding name="HelloServiceSoapBinding" type="tns:HelloService">
        <wsp:PolicyReference URI="#HelloServiceSoapBinding_MTOM_Policy"></wsp:PolicyReference>
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"></soap:binding>
        <operation name="sayHello">
            <soap:operation soapAction="sayHello"></soap:operation>
            <input>
                <soap:body use="literal"></soap:body>
            </input>
            <output>
                <soap:body use="literal"></soap:body>
            </output>
        </operation>
    </binding>
    <binding name="HelloServiceSoapBinding12" type="tns:HelloService">
        <wsp:PolicyReference URI="#HelloServiceSoapBinding_MTOM_Policy"></wsp:PolicyReference>
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="sayHello">
            <soap12:operation soapAction="sayHello"/>
            <input>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="HelloService">
        <port name="HelloServiceSoap" binding="tns:HelloServiceSoapBinding">
            <soap:address location="http://localhost:8080/services/hello-service"></soap:address>
        </port>
        <port name="HelloServiceSoap12" binding="tns:HelloServiceSoapBinding12">
            <soap12:address location="http://localhost:8080/services/hello-service"/>
        </port>
    </service>
</definitions>