# Oracle
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username:
    password:
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource

  sql:
    init:
      mode: never # default embedded
      continue-on-error: true # default false
      # when schema active and use custom HikariDataSource -> exception during pool initialization oracle at oracle.jdbc.driver.PhysicalConnection.setSchema()
      # schema-locations: classpath:db/basic-sql-scripts/schema-oracle.sql
      # data-locations: classpath:db/basic-sql-scripts/data-oralce.sql