#debug: true
spring:
  profiles:
    active: multi
  jpa:
    hibernate:
      ddl-auto: none # This is actually a shortcut for the "hibernate.hbm2ddl.auto" property.
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: create
#          auto: validate
#        format_sql: true