spring:
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    #locations: classpath:db/migration,filesystem:/opt/migration
    check-location: true
    baseline-on-migrate: true
    clean-disabled: true
    #table: flyway_schema_history
    #sql-migration-prefix: V
    #sql-migration-separator: __
    #sql-migration-suffixes: .sql
    #url: ${spring.datasource.url}
    url: jdbc:mysql://localhost:3306/springboot-slave
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    schemas: springboot-master # Override url config schema, spring.flyway.schemas > spring.flyway.url > spring.datasource.url
  liquibase:
    enabled: false