/*
 * This file is generated by jOOQ.
 */
package com.xbw.spring.boot.project.jooq;


import com.xbw.spring.boot.project.jooq.tables.SysJUser;
import com.xbw.spring.boot.project.jooq.tables.Users;
import com.xbw.spring.boot.project.jooq.tables.records.SysJUserRecord;
import com.xbw.spring.boot.project.jooq.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * springboot.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SysJUserRecord> KEY_SYS_J_USER_PRIMARY = Internal.createUniqueKey(SysJUser.SYS_J_USER, DSL.name("KEY_sys_j_user_PRIMARY"), new TableField[] { SysJUser.SYS_J_USER.USER_ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_PRIMARY"), new TableField[] { Users.USERS.USER_ID }, true);
}
