/*
 * This file is generated by jOOQ.
 */
package com.xbw.spring.boot.project.jooq;


import com.xbw.spring.boot.project.jooq.tables.SysJUser;
import com.xbw.spring.boot.project.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Springboot extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>springboot</code>
     */
    public static final Springboot SPRINGBOOT = new Springboot();

    /**
     * The table <code>springboot.sys_j_user</code>.
     */
    public final SysJUser SYS_J_USER = SysJUser.SYS_J_USER;

    /**
     * The table <code>springboot.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Springboot() {
        super("springboot", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            SysJUser.SYS_J_USER,
            Users.USERS);
    }
}
