/*
 * This file is generated by jOOQ.
 */
package com.xbw.spring.boot.project.jooq;


import com.xbw.spring.boot.project.jooq.tables.SysJUser;
import com.xbw.spring.boot.project.jooq.tables.Users;


/**
 * Convenience access to all tables in springboot.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>springboot.sys_j_user</code>.
     */
    public static final SysJUser SYS_J_USER = SysJUser.SYS_J_USER;

    /**
     * The table <code>springboot.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
