/*
 * This file is generated by jOOQ.
 */
package com.xbw.spring.boot.project.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   userId;
    private String userCode;
    private String userName;

    public Users() {}

    public Users(Users value) {
        this.userId = value.userId;
        this.userCode = value.userCode;
        this.userName = value.userName;
    }

    public Users(
        Long   userId,
        String userCode,
        String userName
    ) {
        this.userId = userId;
        this.userCode = userCode;
        this.userName = userName;
    }

    /**
     * Getter for <code>springboot.users.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>springboot.users.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>springboot.users.user_code</code>.
     */
    public String getUserCode() {
        return this.userCode;
    }

    /**
     * Setter for <code>springboot.users.user_code</code>.
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * Getter for <code>springboot.users.user_name</code>.
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>springboot.users.user_name</code>.
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userId);
        sb.append(", ").append(userCode);
        sb.append(", ").append(userName);

        sb.append(")");
        return sb.toString();
    }
}
